---
- name: Create AMI of instances
  hosts: tag_Environment_ec2test
  remote_user: "{{ user }}"
  sudo: True
  sudo_user: root
  roles:
    - AMI_creation
    - security_patch
    - AMI_creation_updated
