---
- name: Stop the instances
  hosts: localhost
  tasks:
    - name: stop the instance
      local_action:
       module: ec2
       instance_tags:
          Environment: ec2test
       state: stopped
       region: us-east-1
      register: ec2

    - debug: var=ec2
 
    - name: create ami
      local_action:
       module: ec2_ami 
       instance_id: "{{ item.id }}"
       wait: yes
       wait_timeout: 600
       with_items:
         - ec2.instances
