---
- name: include variables before_patch
  include_vars: ../vars/before_patch.yml
  when: not patched

- name: include variable after_patch
  include_vars: ../vars/after_patch.yml
  when: patched

- name: Gather facts
  action: ec2_facts
  ignore_errors: True

- debug: var=ansible_ec2_instance_id

- name: stop the instance
  local_action:
   module: ec2
   instance_ids: "{{ ansible_ec2_instance_id }}"
   state: stopped
   region: us-east-1

- name: wait for instance to stop
  pause: minutes=2

- name: create AMI
  local_action:
   module: ec2_ami
   name: mrigank
   instance_id: "{{ ansible_ec2_instance_id }}"
   region: "{{ region }}"
   wait: yes
   tags:
     Name: "{{ AMI_Name }}"

- name: start the instance
  local_action:
   module: ec2
   instance_ids: "{{ ansible_ec2_instance_id }}"
   state: running
   region: us-east-1

- name: wait for instance to start
  pause: minutes=2
