---
- name: Gather facts
  action: ec2_facts
  ignore_errors: True

- debug: var=ansible_ec2_instance_id

- name: stop the instance
  local_action:
   module: ec2
   instance_ids: "{{ ansible_ec2_instance_id }}"
   state: stopped
   region: "{{ region }}"
   wait: true

- name: create AMI
  local_action:
   module: ec2_ami
   name: After_patched
   instance_id: "{{ ansible_ec2_instance_id }}"
   region: "{{ region }}"
   wait: yes
   tags:
     Name: "{{ AMI_Name }}"
     Date: "{{ creation_date }}"

- name: start the instance
  local_action:
   module: ec2
   instance_ids: "{{ ansible_ec2_instance_id }}"
   state: running
   region: "{{ region }}"
   wait: true
