---
#if you want to install the security plugin,then assign the value True to the install_plugin variable.Else if you just want to upgrade the patches, assign Falseto install_plugin variable.
install_plugin: True
